name: Benchmark Regression Check

on:
    pull_request:
      branches: [ main ]
            
jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: make
      # - name: Run benchmark
      #   run: make benchmarks-perf-test
  
  fetch-previous-results_and_compare:
    name: Fetch results
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.18.10'
      - run: make
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          name: benchmark-result-artifact
          name_is_regexp: true
          path: ${{ github.workspace }}
          repo: ${{ github.repository }}
          check_artifacts: false
          search_artifacts: true
          skip_unpack: false
          if_no_artifact_found: fail
          workflow: benchmark_visualization.yml
      - name: Cat Results
        run: cat ${{ github.workspace }}/benchmark-result-artifact/benchmark-result.json