name: Build

on:
  push:
    branches: ['main', 'release/**']
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - '.github/workflows/build.yml'
      - '**.go'
      - 'go.*'
      - 'cmd/go.*'
      - 'Makefile'
      - 'Dockerfile'
      - 'integration/**'
      - 'scripts/**'

env:
  GO_VERSION: '1.21.10'

jobs:
  test:
    runs-on: codebuild-new_soci_CLI-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-xlarge
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make
      - run: make test
  integration:
    runs-on: codebuild-new_soci_CLI-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-7.0-xlarge
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        containerd: ["1.6.30", "1.7.14"]
    env:
      DOCKER_BUILD_ARGS: "CONTAINERD_VERSION=${{ matrix.containerd }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # - run: wget https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-1.7.6-linux-amd64.tar.gz
      # - run: sudo tar Cxzvf /usr/local/bin nerdctl-1.7.6-linux-amd64.tar.gz
      # - run: sudo apt -y update && sudo apt -y upgrade && sudo apt-get -y install gcc-multilib
      # - run: uname -a
      # - run: GO_TEST_FLAGS="-run TestLazyPullWithSparseIndex -count=1" make integration
      - run: GO_TEST_FLAGS="-short -count=1" make integration
