name: Build

on:
  push:
    branches: ['main', 'release/**']
    paths:
      - '**'
      - '!docs/**' # ignore docs changes
      - '!**.md' # ignore markdown changes
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - '.github/workflows/build.yml'
      - '**.go'
      - 'go.*'
      - 'cmd/go.*'
      - 'Makefile'
      - 'Dockerfile'
      - 'integration/**'
      - 'scripts/**'

env:
  GO_VERSION: '1.21.9'

jobs:
  test:
    runs-on: codebuild-soci-snapshotter-personal-pipeline-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-5.0-xlarge
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make
      - run: make test
  integration:
    runs-on: codebuild-soci-snapshotter-personal-pipeline-${{ github.run_id }}-${{ github.run_attempt }}-ubuntu-5.0-xlarge
    strategy:
      fail-fast: false
      matrix:
        containerd: ["1.6.30", "1.7.14"]
    env:
      DOCKER_BUILD_ARGS: "CONTAINERD_VERSION=${{ matrix.containerd }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: sudo rm /usr/local/bin/docker-compose
      # - run: VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | jq .name -r)
      # - run: DESTINATION=/usr/local/bin/docker-compose
      - run: mkdir -p /usr/local/lib/docker/cli-plugins
      - run: sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
      - run: sudo chmod +x  /usr/local/lib/docker/cli-plugins/docker-compose
      - run: ln -s /usr/local/lib/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose
      - run: docker-compose version
      - run: docker compose version
      - run: make integration
